const mongoose = require('mongoose')

/**
 * AI Generated Quiz Model
 * Stores quizzes generated by Gemini API
 */
const aiGeneratedQuizSchema = new mongoose.Schema(
  {
    courseId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Course',
      required: true,
    },
    lessonId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Lesson',
      required: true,
    },
    generatedBy: {
      type: String,
      enum: ['gemini-1.5-flash', 'gemini-1.5-pro', 'manual'],
      default: 'gemini-1.5-flash',
    },
    questions: [
      {
        id: Number,
        question: String,
        type: {
          type: String,
          enum: ['mcq', 'trueFalse', 'shortAnswer'],
        },
        options: [String],
        correctAnswer: mongoose.Schema.Types.Mixed,
        explanation: String,
        difficulty: {
          type: String,
          enum: ['easy', 'intermediate', 'hard'],
        },
        topic: String,
      },
    ],
    metadata: {
      totalQuestions: Number,
      difficulty: String,
      estimatedTimeMinutes: Number,
      generatedAt: Date,
      topic: String,
    },
    instructor: {
      id: mongoose.Schema.Types.ObjectId,
      reviewed: Boolean,
      edited: Boolean,
      approvedAt: Date,
    },
    status: {
      type: String,
      enum: ['draft', 'reviewed', 'approved', 'published'],
      default: 'draft',
    },
    isPublished: {
      type: Boolean,
      default: false,
    },
    studentResponses: [
      {
        userId: mongoose.Schema.Types.ObjectId,
        answers: [mongoose.Schema.Types.Mixed],
        score: Number,
        completedAt: Date,
      },
    ],
    geminiUsageMetadata: {
      inputTokens: Number,
      outputTokens: Number,
      cost: Number,
      processingTimeMs: Number,
    },
  },
  { timestamps: true }
)

/**
 * AI Chat History Model
 * Stores Q&A conversations between students and Gemini
 */
const aiChatHistorySchema = new mongoose.Schema(
  {
    userId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: true,
    },
    courseId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Course',
      required: true,
    },
    lessonId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Lesson',
    },
    conversationId: String,
    messages: [
      {
        role: {
          type: String,
          enum: ['user', 'assistant', 'system'],
        },
        content: String,
        timestamp: Date,
        metadata: {
          tokens: Number,
          cost: Number,
        },
      },
    ],
    summary: String,
    keyTopics: [String],
    flaggedForInstructor: {
      type: Boolean,
      default: false,
    },
    flagReason: String,
    studentSatisfaction: {
      rating: {
        type: Number,
        min: 1,
        max: 5,
      },
      feedback: String,
    },
    totalMessages: Number,
    totalTokensUsed: Number,
    totalCost: Number,
    status: {
      type: String,
      enum: ['active', 'archived', 'escalated'],
      default: 'active',
    },
  },
  { timestamps: true }
)

/**
 * AI Code Review Model
 * Stores code reviews and feedback from Gemini
 */
const aiCodeReviewSchema = new mongoose.Schema(
  {
    userId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: true,
    },
    courseId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Course',
      required: true,
    },
    lessonId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Lesson',
      required: true,
    },
    assignmentId: String,
    submission: {
      code: String,
      language: String,
      fileName: String,
    },
    feedback: {
      score: Number,
      issues: [
        {
          line: Number,
          type: String,
          severity: {
            type: String,
            enum: ['low', 'medium', 'high'],
          },
          description: String,
          suggestion: String,
          explanation: String,
        },
      ],
      strengths: [String],
      improvements: [String],
      bestPractices: [String],
      suggestedRefactoring: String,
      overallFeedback: String,
    },
    instructorReview: {
      reviewed: Boolean,
      overrideScore: Number,
      additionalComments: String,
      reviewedAt: Date,
      reviewedBy: mongoose.Schema.Types.ObjectId,
    },
    geminiUsageMetadata: {
      inputTokens: Number,
      outputTokens: Number,
      cost: Number,
      processingTimeMs: Number,
    },
    studentFeedback: {
      helpful: Boolean,
      comments: String,
    },
  },
  { timestamps: true }
)

/**
 * AI Recommendations Model
 * Stores course/learning path recommendations from Gemini
 */
const aiRecommendationsSchema = new mongoose.Schema(
  {
    userId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: true,
    },
    recommendationType: {
      type: String,
      enum: ['course', 'learningPath', 'nextLesson', 'careerPath'],
    },
    recommendations: [
      {
        id: mongoose.Schema.Types.ObjectId,
        title: String,
        relevanceScore: Number,
        reason: String,
        estimatedTime: String,
        difficulty: String,
        metadata: mongoose.Schema.Types.Mixed,
      },
    ],
    basedOn: {
      completedCourses: [mongoose.Schema.Types.ObjectId],
      interests: [String],
      skillLevel: String,
      goal: String,
    },
    studentAction: {
      clicked: Boolean,
      enrolled: Boolean,
      actionAt: Date,
    },
    geminiUsageMetadata: {
      inputTokens: Number,
      outputTokens: Number,
      cost: Number,
    },
  },
  { timestamps: true }
)

/**
 * AI Generated Learning Path Model
 */
const aiLearningPathSchema = new mongoose.Schema(
  {
    userId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: true,
    },
    courseId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Course',
      required: true,
    },
    pathName: String,
    description: String,
    weeks: [
      {
        weekNumber: Number,
        title: String,
        topics: [String],
        lessons: [
          {
            title: String,
            duration: String,
            type: String,
            description: String,
          },
        ],
        project: {
          title: String,
          description: String,
          difficulty: String,
        },
        estimatedHours: Number,
        difficulty: String,
      },
    ],
    totalDuration: String,
    totalHours: Number,
    prerequisiteSkills: [String],
    keySkillsGained: [String],
    studentProgress: {
      currentWeek: Number,
      completedWeeks: [Number],
      overallProgress: Number,
    },
    geminiUsageMetadata: {
      inputTokens: Number,
      outputTokens: Number,
      cost: Number,
    },
  },
  { timestamps: true }
)

/**
 * AI Summary Model
 * Stores lesson summaries generated by Gemini
 */
const aiSummarySchema = new mongoose.Schema(
  {
    courseId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Course',
      required: true,
    },
    lessonId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Lesson',
      required: true,
    },
    length: {
      type: String,
      enum: ['short', 'medium', 'long'],
    },
    format: {
      type: String,
      enum: ['markdown', 'html', 'plain'],
    },
    summary: String,
    keyPoints: [String],
    definitions: mongoose.Schema.Types.Mixed,
    codeSnippets: [
      {
        title: String,
        code: String,
        explanation: String,
      },
    ],
    studyTips: [String],
    commonMistakes: [String],
    relatedConcepts: [String],
    estimatedReadTime: Number,
    studentViews: Number,
    studentRating: Number,
    geminiUsageMetadata: {
      inputTokens: Number,
      outputTokens: Number,
      cost: Number,
    },
  },
  { timestamps: true }
)

/**
 * AI Generated Course Model
 * Stores course structures generated by Gemini
 */
const aiGeneratedCourseSchema = new mongoose.Schema(
  {
    instructorId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: true,
    },
    courseTitle: String,
    subtitle: String,
    description: String,
    learningObjectives: [String],
    targetAudience: String,
    prerequisites: [String],
    estimatedDuration: String,
    difficulty: String,
    modules: [
      {
        moduleNumber: Number,
        title: String,
        description: String,
        lessons: [
          {
            lessonNumber: Number,
            title: String,
            description: String,
            duration: String,
            topics: [String],
          },
        ],
      },
    ],
    projects: [
      {
        title: String,
        description: String,
        skills: [String],
      },
    ],
    syllabus: String,
    status: {
      type: String,
      enum: ['draft', 'reviewed', 'approved', 'published'],
      default: 'draft',
    },
    instructorEdits: [
      {
        editedAt: Date,
        change: String,
        sections: [String],
      },
    ],
    geminiUsageMetadata: {
      inputTokens: Number,
      outputTokens: Number,
      cost: Number,
    },
  },
  { timestamps: true }
)

// Create indexes for better query performance
aiGeneratedQuizSchema.index({ courseId: 1, lessonId: 1 })
aiGeneratedQuizSchema.index({ 'instructor.approvedAt': 1 })
aiChatHistorySchema.index({ userId: 1, courseId: 1 })
aiChatHistorySchema.index({ createdAt: -1 })
aiCodeReviewSchema.index({ userId: 1, courseId: 1 })
aiLearningPathSchema.index({ userId: 1, courseId: 1 })
aiSummarySchema.index({ courseId: 1, lessonId: 1 })
aiGeneratedCourseSchema.index({ instructorId: 1 })

// Create models
const AIGeneratedQuiz = mongoose.model('AIGeneratedQuiz', aiGeneratedQuizSchema)
const AIChatHistory = mongoose.model('AIChatHistory', aiChatHistorySchema)
const AICodeReview = mongoose.model('AICodeReview', aiCodeReviewSchema)
const AIRecommendations = mongoose.model('AIRecommendations', aiRecommendationsSchema)
const AILearningPath = mongoose.model('AILearningPath', aiLearningPathSchema)
const AISummary = mongoose.model('AISummary', aiSummarySchema)
const AIGeneratedCourse = mongoose.model('AIGeneratedCourse', aiGeneratedCourseSchema)

module.exports = {
  AIGeneratedQuiz,
  AIChatHistory,
  AICodeReview,
  AIRecommendations,
  AILearningPath,
  AISummary,
  AIGeneratedCourse,
}
